/**
 * RockPOS - Point of Sale for PrestaShop.
 *
 * @author    Hamsa Technologies
 * @copyright Hamsa Technologies
 * @license   One license is granted for only one website.
 */

const qzTrayDigitalKey = '-----BEGIN CERTIFICATE-----\n' +
'MIIFGDCCAwCgAwIBAgIQNzkyMDI2MDUwNTA3NTUyOTANBgkqhkiG9w0BAQ0FADCB\n' +
'mDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5ZMRswGQYDVQQKDBJRWiBJbmR1c3Ry\n' +
'aWVzLCBMTEMxGzAZBgNVBAsMElFaIEluZHVzdHJpZXMsIExMQzEZMBcGA1UEAwwQ\n' +
'cXppbmR1c3RyaWVzLmNvbTEnMCUGCSqGSIb3DQEJARYYc3VwcG9ydEBxemluZHVz\n' +
'dHJpZXMuY29tMB4XDTI2MDUwNTA3NTUyOVoXDTI3MDUxNDAzMDIwM1owgdExCzAJ\n' +
'BgNVBAYMAlZOMRYwFAYDVQQIDA1OT1QgQVZBSUxBQkxFMRIwEAYDVQQHDAlIYWkg\n' +
'RHVvbmcxEDAOBgNVBAoMB1JvY2tQT1MxEDAOBgNVBAsMB1JvY2tQT1MxEDAOBgNV\n' +
'BAMMB1JvY2tQT1MxIjAgBgkqhkiG9w0BCQEME3N1cHBvcnRAcm9ja3Bvcy5jb20x\n' +
'PDA6BgNVBA0MM3JlbmV3YWwtb2YtMjNlZjhlZDA4M2Y0YzBmZGQyM2Y1ODFjMTcz\n' +
'ZjE4NDBiMDRjMDU5MTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ8X\n' +
'IY6JpNJfcMi+unBEqavFzgntdqHER/P29ftmz6Bb3RmExT3u1DantqfkspVl65TB\n' +
'+eK9VDeB8aoG1Gut6LbEqOQyTb8S8Gx6izasUwqZaB2acVA/W2xaIoPmvLl/vjSl\n' +
'gmqnfUp5GkoQlKKdqCisH4I/ch8Ov8kFZJXsM9t5jBxljPnED/uPiY7Mek9QbbgN\n' +
'p1yf+/tIX0E+Ap5gRyTxjFUCFMeoTJYKus/KFUcjyA/xBfaN9LtTCzpEQu4aQgP6\n' +
'g8Y4g3mf/w6QlC6Aq+WZCzWlOFV6x1K6GuYfY1t4g7hgr392bj308bN8bVTdZnmU\n' +
'OCSN9Wv5KS+1bKZyCE8CAwEAAaMjMCEwHwYDVR0jBBgwFoAUkKZQt4TUuepf8gWE\n' +
'E3hF6Kl1VFwwDQYJKoZIhvcNAQENBQADggIBANNuS3CLTKZVzk+VF108NuLCDZH/\n' +
'rV+n81p6N40eThLHqSrDrSeO7CVTTVddqb8Y1UU+DWM+OsTIVShbN9BaTE0gZNAP\n' +
'KGRbqfXE3vsnTAnmKNyRjfnLLG1gfGqWOch3XXoQWZgWu6wvA5RSetO7ue8ncPMr\n' +
'Qi1irazNB2+Pz2w2XgcznRZRI16B2SixhzVmCCpclC034o+Z1hhgSRwKHcma3A5A\n' +
'MTG/qlLglBmWWVdqJRdS2eRUvN0Yay0lvHAj1MHSOy0ITADMmc02n+6b97NYJnxS\n' +
'O1qTTg1YfjhltBp6Czwmseu/fNcoHwN2E3jfNQt/S9/9ICfybJdHZR3pEgyciO9i\n' +
'PeCO90KuOcgDgLQlUth/Yj1hx+/0XFatSmuNQCUTBSRqgHwgyJD50HyxERIpCzSo\n' +
'48MtSq5AN5+ANlbEDgdTyVZx541FBbyFTjfn8sBEsvJzj4kaWI1pnkDEbBquJ7GY\n' +
'xSHb9PkTzlSBrqeOMtZRR/fBy7nbJ/NuRG5Elwxuyk6Mo9esl8lrv0ldtVhIwgfy\n' +
'nG4d3x4ibJRC8M1sAAf2MNv/cgfRcN4kdMJ7xSAvsG1hC1wWpy+LjnQMLVPaRKEi\n' +
'UzWnnWMedrTyYIuseCNpsv0qk54t0ewVbvRf/laO1zksc7CF0QqN82+Xfw2hZ7Tz\n' +
'YKPor6J/8YU+uaXv\n' +
'-----END CERTIFICATE-----\n' +
'--START INTERMEDIATE CERT--\n' +
'-----BEGIN CERTIFICATE-----\n' +
'MIIFEjCCA/qgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgawxCzAJBgNVBAYTAlVT\n' +
'MQswCQYDVQQIDAJOWTESMBAGA1UEBwwJQ2FuYXN0b3RhMRswGQYDVQQKDBJRWiBJ\n' +
'bmR1c3RyaWVzLCBMTEMxGzAZBgNVBAsMElFaIEluZHVzdHJpZXMsIExMQzEZMBcG\n' +
'A1UEAwwQcXppbmR1c3RyaWVzLmNvbTEnMCUGCSqGSIb3DQEJARYYc3VwcG9ydEBx\n' +
'emluZHVzdHJpZXMuY29tMB4XDTE1MDMwMjAwNTAxOFoXDTM1MDMwMjAwNTAxOFow\n' +
'gZgxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOWTEbMBkGA1UECgwSUVogSW5kdXN0\n' +
'cmllcywgTExDMRswGQYDVQQLDBJRWiBJbmR1c3RyaWVzLCBMTEMxGTAXBgNVBAMM\n' +
'EHF6aW5kdXN0cmllcy5jb20xJzAlBgkqhkiG9w0BCQEWGHN1cHBvcnRAcXppbmR1\n' +
'c3RyaWVzLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANTDgNLU\n' +
'iohl/rQoZ2bTMHVEk1mA020LYhgfWjO0+GsLlbg5SvWVFWkv4ZgffuVRXLHrwz1H\n' +
'YpMyo+Zh8ksJF9ssJWCwQGO5ciM6dmoryyB0VZHGY1blewdMuxieXP7Kr6XD3GRM\n' +
'GAhEwTxjUzI3ksuRunX4IcnRXKYkg5pjs4nLEhXtIZWDLiXPUsyUAEq1U1qdL1AH\n' +
'EtdK/L3zLATnhPB6ZiM+HzNG4aAPynSA38fpeeZ4R0tINMpFThwNgGUsxYKsP9kh\n' +
'0gxGl8YHL6ZzC7BC8FXIB/0Wteng0+XLAVto56Pyxt7BdxtNVuVNNXgkCi9tMqVX\n' +
'xOk3oIvODDt0UoQUZ/umUuoMuOLekYUpZVk4utCqXXlB4mVfS5/zWB6nVxFX8Io1\n' +
'9FOiDLTwZVtBmzmeikzb6o1QLp9F2TAvlf8+DIGDOo0DpPQUtOUyLPCh5hBaDGFE\n' +
'ZhE56qPCBiQIc4T2klWX/80C5NZnd/tJNxjyUyk7bjdDzhzT10CGRAsqxAnsjvMD\n' +
'2KcMf3oXN4PNgyfpbfq2ipxJ1u777Gpbzyf0xoKwH9FYigmqfRH2N2pEdiYawKrX\n' +
'6pyXzGM4cvQ5X1Yxf2x/+xdTLdVaLnZgwrdqwFYmDejGAldXlYDl3jbBHVM1v+uY\n' +
'5ItGTjk+3vLrxmvGy5XFVG+8fF/xaVfo5TW5AgMBAAGjUDBOMB0GA1UdDgQWBBSQ\n' +
'plC3hNS56l/yBYQTeEXoqXVUXDAfBgNVHSMEGDAWgBQDRcZNwPqOqQvagw9BpW0S\n' +
'BkOpXjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAJIO8SiNr9jpLQ\n' +
'eUsFUmbueoxyI5L+P5eV92ceVOJ2tAlBA13vzF1NWlpSlrMmQcVUE/K4D01qtr0k\n' +
'gDs6LUHvj2XXLpyEogitbBgipkQpwCTJVfC9bWYBwEotC7Y8mVjjEV7uXAT71GKT\n' +
'x8XlB9maf+BTZGgyoulA5pTYJ++7s/xX9gzSWCa+eXGcjguBtYYXaAjjAqFGRAvu\n' +
'pz1yrDWcA6H94HeErJKUXBakS0Jm/V33JDuVXY+aZ8EQi2kV82aZbNdXll/R6iGw\n' +
'2ur4rDErnHsiphBgZB71C5FD4cdfSONTsYxmPmyUb5T+KLUouxZ9B0Wh28ucc1Lp\n' +
'rbO7BnjW\n' +
'-----END CERTIFICATE-----'